### ISSUE TITLE
Incompatible with Rails 5

### ISSUE THREAD

**Issue by adsteel** [codegram/resort#15]
Currently `resort` depends on `ActiveRecord ~> 4`. With Rails 5.0.0.beta1 released, looks like it may be time to test `resort` with the new ActiveRecord 5.

http://weblog.rubyonrails.org/2015/12/18/Rails-5-0-beta1/

**Comment by oriolgual** [comment]
Starting from version 0.6 resort is compatible with Rails 5! (I'll release it in a few minutes).
